- name: Prepare site
  env:
    COMMIT_SHA: ${{ github.sha }}
    BASE_URL: https://ckpalmer.github.io/BB19
  run: |
    mkdir -p _site
    cp *.json _site/ || true

    # Build index.html with cache-busting + no-cache headers (via meta)
    cat > _site/index.html <<'HTML'
    <!doctype html>
    <meta charset="utf-8">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>BB19 Data Bank</title>
    <h1>BB19 Data Bank (newest → oldest)</h1>
    <p>Each link adds a cache-busting query tied to the latest commit so updates show immediately.</p>
    <ul id="links"></ul>
    <script>
      const v = '${{ github.sha }}'.slice(0, 8);
      const files = [
        'master.json','checkins.json',
        'phase0.json','phase1.json','phase2.json','phase3.json','phase4.json','phase5.json'
      ];
      const ul = document.getElementById('links');
      files.forEach(f => {
        const li = document.createElement('li');
        const a = document.createElement('a');
        a.href = f + '?v=' + v;
        a.textContent = f;
        li.appendChild(a);
        ul.appendChild(li);
      });
    </script>
    <p>Convention: arrays are globally forced to newest-first.</p>
    HTML

    # Build sitemap.xml (updated each deploy)
    cat > _site/sitemap.xml <<SITEMAP
    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      <url><loc>${BASE_URL}/</loc><changefreq>always</changefreq><priority>0.5</priority></url>
      <url><loc>${BASE_URL}/master.json</loc><changefreq>always</changefreq><priority>0.9</priority></url>
      <url><loc>${BASE_URL}/checkins.json</loc><changefreq>always</changefreq><priority>0.9</priority></url>
      <url><loc>${BASE_URL}/phase0.json</loc><changefreq>always</changefreq><priority>0.8</priority></url>
      <url><loc>${BASE_URL}/phase1.json</loc><changefreq>always</changefreq><priority>0.8</priority></url>
      <url><loc>${BASE_URL}/phase2.json</loc><changefreq>always</changefreq><priority>0.8</priority></url>
      <url><loc>${BASE_URL}/phase3.json</loc><changefreq>always</changefreq><priority>0.8</priority></url>
      <url><loc>${BASE_URL}/phase4.json</loc><changefreq>always</changefreq><priority>0.8</priority></url>
      <url><loc>${BASE_URL}/phase5.json</loc><changefreq>always</changefreq><priority>0.8</priority></url>
    </urlset>
    SITEMAP

    # robots.txt that points to sitemap
    cat > _site/robots.txt <<ROBOTS
    User-agent: *
    Allow: /
    Sitemap: ${BASE_URL}/sitemap.xml
    ROBOTS
