- name: Prepare site
  run: |
    mkdir -p _site
    cp *.json _site/ || true
    cat > _site/index.html <<'HTML'
    <!doctype html>
    <meta charset="utf-8">
    <title>BB19 Data Bank</title>
    <h1>BB19 Data Bank (newest → oldest)</h1>
    <ul>
      <li><a href="master.json">master.json</a></li>
      <li><a href="checkins.json">checkins.json</a></li>
      <li><a href="phase0.json">phase0.json</a></li>
      <li><a href="phase1.json">phase1.json</a></li>
      <li><a href="phase2.json">phase2.json</a></li>
      <li><a href="phase3.json">phase3.json</a></li>
      <li><a href="phase4.json">phase4.json</a></li>
      <li><a href="phase5.json">phase5.json</a></li>
    </ul>
    <p>Convention: rows are globally forced to newest-first.</p>
    HTML

